// <auto-generated />
using System;
using HelloMotors.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelloMotors.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HelloMotors.Model.Proprietario", b =>
                {
                    b.Property<int>("IdProprietario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProprietario"));

                    b.Property<string>("CpfCnpj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DadosPessoais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProprietario");

                    b.ToTable("Proprietarios");
                });

            modelBuilder.Entity("HelloMotors.Model.Veiculo", b =>
                {
                    b.Property<int>("IdChassi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChassi"));

                    b.Property<string>("Acessorios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<string>("Chassi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Cor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdProprietario")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProprietarioIdProprietario")
                        .HasColumnType("int");

                    b.Property<decimal>("Quilometragem")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VersaoSistema")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdChassi");

                    b.HasIndex("ProprietarioIdProprietario");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("HelloMotors.Model.Venda", b =>
                {
                    b.Property<int>("IdVenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVenda"));

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdChassi")
                        .HasColumnType("int");

                    b.Property<int>("IdVendedor")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("VeiculoIdChassi")
                        .HasColumnType("int");

                    b.Property<int?>("VendedorIdVendedor")
                        .HasColumnType("int");

                    b.HasKey("IdVenda");

                    b.HasIndex("VeiculoIdChassi");

                    b.HasIndex("VendedorIdVendedor");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("HelloMotors.Model.Vendedor", b =>
                {
                    b.Property<int>("IdVendedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVendedor"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SalarioBase")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdVendedor");

                    b.ToTable("Vendedores");
                });

            modelBuilder.Entity("HelloMotors.Model.Veiculo", b =>
                {
                    b.HasOne("HelloMotors.Model.Proprietario", "Proprietario")
                        .WithMany()
                        .HasForeignKey("ProprietarioIdProprietario");

                    b.Navigation("Proprietario");
                });

            modelBuilder.Entity("HelloMotors.Model.Venda", b =>
                {
                    b.HasOne("HelloMotors.Model.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoIdChassi");

                    b.HasOne("HelloMotors.Model.Vendedor", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorIdVendedor");

                    b.Navigation("Veiculo");

                    b.Navigation("Vendedor");
                });
#pragma warning restore 612, 618
        }
    }
}
